// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.serialize;

public final class Product {
  private Product() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProductInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ProductInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string s1 = 1;</code>
     */
    boolean hasS1();
    /**
     * <code>optional string s1 = 1;</code>
     */
    java.lang.String getS1();
    /**
     * <code>optional string s1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getS1Bytes();

    /**
     * <code>optional int32 i2 = 2;</code>
     */
    boolean hasI2();
    /**
     * <code>optional int32 i2 = 2;</code>
     */
    int getI2();

    /**
     * <code>optional bool b3 = 3;</code>
     */
    boolean hasB3();
    /**
     * <code>optional bool b3 = 3;</code>
     */
    boolean getB3();

    /**
     * <code>repeated string list = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getListList();
    /**
     * <code>repeated string list = 4;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 4;</code>
     */
    java.lang.String getList(int index);
    /**
     * <code>repeated string list = 4;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.ProductInfo}
   */
  public  static final class ProductInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.ProductInfo)
      ProductInfoOrBuilder {
    // Use ProductInfo.newBuilder() to construct.
    private ProductInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private ProductInfo() {
      s1_ = "";
      i2_ = 0;
      b3_ = false;
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              s1_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              i2_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              b3_ = input.readBool();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              list_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = list_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.serialize.Product.internal_static_tutorial_ProductInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.serialize.Product.internal_static_tutorial_ProductInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.serialize.Product.ProductInfo.class, com.serialize.Product.ProductInfo.Builder.class);
    }

    public static final com.google.protobuf.Parser<ProductInfo> PARSER =
        new com.google.protobuf.AbstractParser<ProductInfo>() {
      public ProductInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProductInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S1_FIELD_NUMBER = 1;
    private java.lang.Object s1_;
    /**
     * <code>optional string s1 = 1;</code>
     */
    public boolean hasS1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string s1 = 1;</code>
     */
    public java.lang.String getS1() {
      java.lang.Object ref = s1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getS1Bytes() {
      java.lang.Object ref = s1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int I2_FIELD_NUMBER = 2;
    private int i2_;
    /**
     * <code>optional int32 i2 = 2;</code>
     */
    public boolean hasI2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 i2 = 2;</code>
     */
    public int getI2() {
      return i2_;
    }

    public static final int B3_FIELD_NUMBER = 3;
    private boolean b3_;
    /**
     * <code>optional bool b3 = 3;</code>
     */
    public boolean hasB3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool b3 = 3;</code>
     */
    public boolean getB3() {
      return b3_;
    }

    public static final int LIST_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 4;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getS1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, i2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, b3_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(4, list_.getByteString(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getS1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, i2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, b3_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.serialize.Product.ProductInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serialize.Product.ProductInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serialize.Product.ProductInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.serialize.Product.ProductInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.serialize.Product.ProductInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serialize.Product.ProductInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.serialize.Product.ProductInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.serialize.Product.ProductInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.serialize.Product.ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.serialize.Product.ProductInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.serialize.Product.ProductInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ProductInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ProductInfo)
        com.serialize.Product.ProductInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.serialize.Product.internal_static_tutorial_ProductInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.serialize.Product.internal_static_tutorial_ProductInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.serialize.Product.ProductInfo.class, com.serialize.Product.ProductInfo.Builder.class);
      }

      // Construct using com.serialize.Product.ProductInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        s1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        i2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        b3_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.serialize.Product.internal_static_tutorial_ProductInfo_descriptor;
      }

      public com.serialize.Product.ProductInfo getDefaultInstanceForType() {
        return com.serialize.Product.ProductInfo.getDefaultInstance();
      }

      public com.serialize.Product.ProductInfo build() {
        com.serialize.Product.ProductInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.serialize.Product.ProductInfo buildPartial() {
        com.serialize.Product.ProductInfo result = new com.serialize.Product.ProductInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s1_ = s1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.i2_ = i2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.b3_ = b3_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = list_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.list_ = list_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.serialize.Product.ProductInfo) {
          return mergeFrom((com.serialize.Product.ProductInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.serialize.Product.ProductInfo other) {
        if (other == com.serialize.Product.ProductInfo.getDefaultInstance()) return this;
        if (other.hasS1()) {
          bitField0_ |= 0x00000001;
          s1_ = other.s1_;
          onChanged();
        }
        if (other.hasI2()) {
          setI2(other.getI2());
        }
        if (other.hasB3()) {
          setB3(other.getB3());
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.serialize.Product.ProductInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.serialize.Product.ProductInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object s1_ = "";
      /**
       * <code>optional string s1 = 1;</code>
       */
      public boolean hasS1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string s1 = 1;</code>
       */
      public java.lang.String getS1() {
        java.lang.Object ref = s1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getS1Bytes() {
        java.lang.Object ref = s1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s1 = 1;</code>
       */
      public Builder setS1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        s1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s1 = 1;</code>
       */
      public Builder clearS1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s1_ = getDefaultInstance().getS1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s1 = 1;</code>
       */
      public Builder setS1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        s1_ = value;
        onChanged();
        return this;
      }

      private int i2_ ;
      /**
       * <code>optional int32 i2 = 2;</code>
       */
      public boolean hasI2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 i2 = 2;</code>
       */
      public int getI2() {
        return i2_;
      }
      /**
       * <code>optional int32 i2 = 2;</code>
       */
      public Builder setI2(int value) {
        bitField0_ |= 0x00000002;
        i2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 i2 = 2;</code>
       */
      public Builder clearI2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        i2_ = 0;
        onChanged();
        return this;
      }

      private boolean b3_ ;
      /**
       * <code>optional bool b3 = 3;</code>
       */
      public boolean hasB3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool b3 = 3;</code>
       */
      public boolean getB3() {
        return b3_;
      }
      /**
       * <code>optional bool b3 = 3;</code>
       */
      public Builder setB3(boolean value) {
        bitField0_ |= 0x00000004;
        b3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool b3 = 3;</code>
       */
      public Builder clearB3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        b3_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListList() {
        return list_.getUnmodifiableView();
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public java.lang.String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder setList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<java.lang.String> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 4;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.ProductInfo)
    }

    // @@protoc_insertion_point(class_scope:tutorial.ProductInfo)
    private static final com.serialize.Product.ProductInfo defaultInstance;static {
      defaultInstance = new com.serialize.Product.ProductInfo();
    }

    public static com.serialize.Product.ProductInfo getDefaultInstance() {
      return defaultInstance;
    }

    public com.serialize.Product.ProductInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ProductInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ProductInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\010tutorial\"?\n\013ProductInfo" +
      "\022\n\n\002s1\030\001 \001(\t\022\n\n\002i2\030\002 \001(\005\022\n\n\002b3\030\003 \001(\010\022\014\n\004" +
      "list\030\004 \003(\tB\030\n\rcom.serializeB\007Product"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_ProductInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_ProductInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_ProductInfo_descriptor,
        new java.lang.String[] { "S1", "I2", "B3", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
